/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterface;

import javax.swing.JOptionPane;

/**
 *
 * @author SANTI
 */
public class WinAgenda extends javax.swing.JFrame {
    WinAbrir abrir=new WinAbrir();
    /**
     * Creates new form WinAgenda
     */
    public WinAgenda() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAgenda = new javax.swing.JMenu();
        JItemNueva = new javax.swing.JMenuItem();
        JItemAbrir = new javax.swing.JMenuItem();
        MenuContacto = new javax.swing.JMenu();
        JItemAgregar = new javax.swing.JMenuItem();
        JItemEditar = new javax.swing.JMenuItem();
        JItemEliminar = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();
        JItemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacion de Agendas");

        MenuAgenda.setText("AGENDA");
        MenuAgenda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        JItemNueva.setText("Nueva");
        JItemNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemNuevaActionPerformed(evt);
            }
        });
        MenuAgenda.add(JItemNueva);

        JItemAbrir.setText("Abrir");
        JItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemAbrirActionPerformed(evt);
            }
        });
        MenuAgenda.add(JItemAbrir);

        jMenuBar1.add(MenuAgenda);

        MenuContacto.setText("CONTACTO");
        MenuContacto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        JItemAgregar.setText("Agregar");
        JItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemAgregarActionPerformed(evt);
            }
        });
        MenuContacto.add(JItemAgregar);

        JItemEditar.setText("Editar");
        JItemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemEditarActionPerformed(evt);
            }
        });
        MenuContacto.add(JItemEditar);

        JItemEliminar.setText("Eliminar");
        JItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemEliminarActionPerformed(evt);
            }
        });
        MenuContacto.add(JItemEliminar);

        jMenuBar1.add(MenuContacto);

        MenuAyuda.setText("AYUDA");
        MenuAyuda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        JItemAcerca.setText("Acerca de...");
        JItemAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemAcercaActionPerformed(evt);
            }
        });
        MenuAyuda.add(JItemAcerca);

        jMenuBar1.add(MenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JItemNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemNuevaActionPerformed
        WinNueva nueva = new WinNueva();
        nueva.setVisible(true);
       // this.setVisible(false);
    }//GEN-LAST:event_JItemNuevaActionPerformed

    private void JItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemAbrirActionPerformed
        
        abrir.setVisible(true);
       // this.setVisible(false);
    }//GEN-LAST:event_JItemAbrirActionPerformed

    private void JItemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemAgregarActionPerformed
        WinAgregar abrir = new WinAgregar();
        abrir.setVisible(true);
    }//GEN-LAST:event_JItemAgregarActionPerformed

    private void JItemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemEditarActionPerformed
        WinEditar abrir = new WinEditar();
        abrir.setVisible(true);
    }//GEN-LAST:event_JItemEditarActionPerformed

    private void JItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemEliminarActionPerformed
        WinEliminar abrir = new WinEliminar();
        abrir.setVisible(true);
    }//GEN-LAST:event_JItemEliminarActionPerformed

    private void JItemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemAcercaActionPerformed
        JOptionPane.showMessageDialog(null, "Bievenido a esta Aplicacion para crear agendas de Contactos");
    }//GEN-LAST:event_JItemAcercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JItemAbrir;
    private javax.swing.JMenuItem JItemAcerca;
    private javax.swing.JMenuItem JItemAgregar;
    private javax.swing.JMenuItem JItemEditar;
    private javax.swing.JMenuItem JItemEliminar;
    private javax.swing.JMenuItem JItemNueva;
    private javax.swing.JMenu MenuAgenda;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuContacto;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
